# Generated by Django 5.1.1 on 2024-11-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Compromisso', 'verbose_name_plural': 'Agenda'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='age_descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='eve_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abi.evento', verbose_name='Evento'),
        ),
    ]
