# Generated by Django 5.1.1 on 2024-12-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pes_cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
