# Generated by Django 5.1.1 on 2024-12-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='age_titulo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
