# Generated by Django 5.1.4 on 2025-01-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eve_participantes',
            field=models.ManyToManyField(related_name='Participantes', to='abi.pessoa'),
        ),
    ]
