# Generated by Django 5.1.1 on 2024-12-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0002_agenda_age_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='age_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
