# Generated by Django 5.1.4 on 2025-01-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0002_evento_eve_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cid_naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naturalidade', to='abi.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='est_naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naturalidade', to='abi.estado', verbose_name='Estado'),
        ),
    ]
