# Generated by Django 5.1.1 on 2024-11-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0002_alter_agenda_options_alter_agenda_age_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areapesquisa',
            name='ape_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='age_descricao',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
    ]
