# Generated by Django 5.1.4 on 2025-01-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0003_alter_pessoa_cid_naturalidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoXPessoa',
        ),
    ]
