# Generated by Django 5.1.1 on 2024-12-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0003_alter_pessoa_pes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cid_cod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abi.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='end_bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='end_complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='end_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='end_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='end_rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='est_cod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abi.estado', verbose_name='Estado'),
        ),
    ]
