# Generated by Django 5.1.1 on 2024-11-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0003_areapesquisa_ape_ativo_alter_agenda_age_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areapesquisa',
            name='ape_ativo',
        ),
    ]
