# Generated by Django 5.1.1 on 2024-11-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0003_areapesquisa_ape_ativo_alter_agenda_age_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pai_cod', models.AutoField(primary_key=True, serialize=False)),
                ('pai_sigla', models.CharField(max_length=2, verbose_name='Sigla do País')),
                ('pai_descricao', models.CharField(max_length=100, verbose_name='País')),
            ],
        ),
        migrations.RemoveField(
            model_name='areapesquisa',
            name='ape_ativo',
        ),
    ]
