# Generated by Django 5.1.1 on 2024-11-10 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0004_remove_areapesquisa_ape_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cur_cod', models.AutoField(primary_key=True, serialize=False)),
                ('cur_descricao', models.CharField(max_length=255, verbose_name='Curso')),
                ('cur_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='areaartistica',
            options={'verbose_name': 'Campo Artistico', 'verbose_name_plural': 'Campo Artistico'},
        ),
        migrations.AlterModelOptions(
            name='etnia',
            options={'verbose_name': 'Etnia/Raça', 'verbose_name_plural': 'Etnias/Raças'},
        ),
        migrations.AddField(
            model_name='bolsista',
            name='bol_tema',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tema de PEsquisa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pes_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pes_numero',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='areaartistica',
            name='are_descricao',
            field=models.CharField(max_length=255, verbose_name='Campo Artistico'),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='etn_descricao',
            field=models.CharField(max_length=255, verbose_name='Etnia/Raça'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='are_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.areaartistica', verbose_name='Campo Artistico'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cid_naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naturalidade', to='abi.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='end_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='esc_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.escolaridade', verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='est_naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naturalidade', to='abi.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='etn_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.etnia', verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='gen_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ori_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.orientacaosexual', verbose_name='Orientação Sexual'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pes_data_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ingresso'),
        ),
        migrations.CreateModel(
            name='Oficineiro',
            fields=[
                ('ofc_cod', models.AutoField(primary_key=True, serialize=False)),
                ('ofc_descricao', models.CharField(max_length=255, verbose_name='Nome da Oficina')),
                ('ofc_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pes_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abi.pessoa', verbose_name='Integrante')),
            ],
        ),
    ]
