# Generated by Django 5.1.1 on 2024-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0004_pais_remove_areapesquisa_ape_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='age_descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
    ]
