# Generated by Django 5.1.4 on 2025-01-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0004_delete_eventoxpessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='eve_participantes',
            new_name='Participantes',
        ),
    ]
