# Generated by Django 5.1.4 on 2025-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0005_rename_eve_participantes_evento_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='age_titulo',
            field=models.CharField(default='Compromisso', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='Participantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Participantes', to='abi.pessoa'),
        ),
    ]
