# Generated by Django 5.1.1 on 2024-11-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0005_curso_alter_areaartistica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='cur_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='bol_tema',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tema de Pesquisa'),
        ),
    ]
