# Generated by Django 5.1.1 on 2024-11-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0006_bolsista_cur_cod_alter_bolsista_bol_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='etn_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abi.etnia', verbose_name='Etnia/Raça'),
        ),
    ]
