# Generated by Django 5.1.1 on 2024-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0006_pessoa_pes_celular_pessoa_pes_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pes_celular',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pes_email',
            field=models.CharField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pes_telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
