# Generated by Django 5.1.4 on 2025-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0006_agenda_age_titulo_alter_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='age_titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
