# Generated by Django 5.1.4 on 2025-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0007_alter_agenda_age_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='age_descricao',
            field=models.TextField(max_length=1000, verbose_name='Descrição'),
        ),
    ]
