# Generated by Django 5.1.1 on 2024-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0007_alter_pessoa_pes_celular_alter_pessoa_pes_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='abi_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
    ]
