# Generated by Django 5.1.1 on 2024-11-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0007_alter_pessoa_etn_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='est_naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naturalidade', to='abi.estado', verbose_name='Estado'),
        ),
    ]
