# Generated by Django 5.1.4 on 2025-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0008_alter_agenda_age_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('ofc_cod', models.AutoField(primary_key=True, serialize=False)),
                ('ofc_titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('ofc_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
