# Generated by Django 5.1.1 on 2024-11-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0008_pessoa_abi_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='abi_imagem',
            new_name='pes_imagem',
        ),
    ]
