# Generated by Django 5.1.1 on 2024-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0009_alter_pessoa_est_naturalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='ofi_numero',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do Ofício'),
        ),
    ]
