# Generated by Django 5.1.4 on 2025-01-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0009_oficinas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oficinas',
            new_name='Oficina',
        ),
    ]
