# Generated by Django 5.1.4 on 2025-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0010_rename_oficinas_oficina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficineiro',
            name='ofc_descricao',
        ),
        migrations.AddField(
            model_name='oficineiro',
            name='Oficinas',
            field=models.ManyToManyField(to='abi.oficina', verbose_name='Oficinas'),
        ),
    ]
