# Generated by Django 5.1.1 on 2024-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0010_alter_oficio_ofi_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='ofi_numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número do Ofício'),
        ),
    ]
