# Generated by Django 5.1.1 on 2024-11-23 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0010_usuariopessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoa',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='abi.pessoa'),
        ),
    ]
