# Generated by Django 5.1.1 on 2024-11-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0011_alter_usuariopessoa_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPessoa',
        ),
    ]
