# Generated by Django 5.1.1 on 2024-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0011_alter_oficio_ofi_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='age_titulo',
            field=models.CharField(default='Vazio', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='ofi_numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do Ofício'),
        ),
    ]
