# Generated by Django 5.1.4 on 2025-01-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0011_remove_oficineiro_ofc_descricao_oficineiro_oficinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pes_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/integrantes', verbose_name='Imagem'),
        ),
    ]
