# Generated by Django 5.1.4 on 2025-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0012_alter_pessoa_pes_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pes_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/integrantes/', verbose_name='Imagem'),
        ),
    ]
