# Generated by Django 5.1.1 on 2024-11-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0012_agenda_age_titulo_alter_oficio_ofi_numero'),
        ('abi', '0012_delete_usuariopessoa'),
    ]

    operations = [
    ]
