# Generated by Django 5.1.1 on 2024-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0012_agenda_age_titulo_alter_oficio_ofi_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='age_titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
