# Generated by Django 5.1.1 on 2024-11-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0013_alter_agenda_age_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='eve_data_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Retorno'),
        ),
    ]
