# Generated by Django 5.1.1 on 2024-11-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0014_usuariopessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopessoa',
            old_name='pessoa',
            new_name='pessoaa',
        ),
    ]
