# Generated by Django 5.1.1 on 2024-11-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0015_rename_pessoa_usuariopessoa_pessoaa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPessoa',
        ),
    ]
