# Generated by Django 5.1.1 on 2024-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0016_delete_usuariopessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='age_titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pes_numero',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Número'),
        ),
    ]
