# Generated by Django 5.1.1 on 2024-11-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0020_alter_usuariopessoa_pessoa_alter_usuariopessoa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoa',
            name='pessoa',
            field=models.ForeignKey(db_column='pes_cod', on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='abi.pessoa'),
        ),
    ]
