# Generated by Django 5.1.1 on 2024-11-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0021_alter_usuariopessoa_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopessoa',
            old_name='pessoa',
            new_name='pes_cod',
        ),
    ]
