# Generated by Django 5.1.1 on 2024-11-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0022_rename_pessoa_usuariopessoa_pes_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoa',
            name='pes_cod',
            field=models.ForeignKey(blank=True, db_column='pes_cod', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='abi.pessoa'),
        ),
    ]
