# Generated by Django 5.1.1 on 2024-11-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0014_alter_evento_eve_data_retorno'),
        ('abi', '0024_alter_usuariopessoa_user'),
    ]

    operations = [
    ]
